language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - COVERAGE=true

script: "rake ci"

notifications:
  irc: "irc.freenode.org#ndlib"

bundler_args: --without headless

before_install:
  - gem install bundler
